--- 
- name: replace testfile.txt
  copy:
    dest: /tmp/testfile.txt
    content: "var1: {{my_var1}} and var2: {{my_var2}} \n"
  register: index_file

- name: output index_file var contents
  debug: 
    msg: "{{index_file}}"