---
- name: replace testfile.txt
  tags: first_part
  copy:
    dest: /tmp/testfile.txt
    content: "Hi, I am host {{ansible_hostname}} 
    and I run the linux kernel {{ ansible_kernel }} \n
    Var1a: {{my_var1a}} \n
    Var1b: {{my_var1b}} \n
    Var2: {{my_var2}} \n
    Var3: {{my_var3}} \n
    Var4: {{my_var4}} \n"
  register: index_file

- name: replace testfile.txt
  tags: second_part
  copy: 
    dest: /tmp/testfile.txt
    content: " Var5: {{my_var5}}\n"
  register: index_file
